spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/ykyzl?useSSL=false&useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password:
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0